import { Utility } from '@/mock-data/types';

const paymentHistory: Utility[] = [
    {
        id: 1,
        account: '12345',
        organization: 'Енерго компанія',
        service: 'Електрика',
        imageUri: '',
        readings: [
            { id: 1, reading: 100, date: '2023-06-25' },
            { id: 2, reading: 120, date: '2023-07-25' },
        ],
        payments: [
            { id: 1, sum: 100, date: '2023-06-25' },
            { id: 2, sum: 120, date: '2023-07-25' },
            { id: 3, sum: 420, date: '2023-05-25' },
            { id: 4, sum: 320, date: '2023-04-25' },
        ],
    },
    {
        id: 2,
        account: '67890',
        organization: 'Водяна компанія',
        service: 'Вода',
        imageUri: '',
        readings: [
            { id: 1, reading: 50, date: '2023-06-25' },
            { id: 2, reading: 60, date: '2023-07-25' },
        ],
        payments: [
            { id: 1, sum: 100, date: '2023-06-25' },
            { id: 2, sum: 120, date: '2023-07-25' },
        ],
    },
    {
        id: 3,
        account: '12890',
        organization: 'Газована компанія',
        service: 'Газ',
        imageUri: '',
        readings: [
            { id: 1, reading: 30, date: '2023-06-25' },
            { id: 2, reading: 70, date: '2023-07-25' },
        ],
        payments: [
            { id: 1, sum: 100, date: '2023-06-25' },
            { id: 2, sum: 120, date: '2023-07-25' },
        ],
    },
    {
        id: 4,
        account: '25220',
        organization: 'Інтернет компанія',
        service: 'Інтернет',
        imageUri: '',
        readings: [
            { id: 1, reading: 100, date: '2023-06-25' },
            { id: 2, reading: 200, date: '2023-07-25' },
        ],
        payments: [
            { id: 1, sum: 100, date: '2023-06-25' },
            { id: 2, sum: 120, date: '2023-07-25' },
            { id: 3, sum: 1120, date: '2023-08-25' },
            { id: 4, sum: 920, date: '2023-08-29' },
        ],
    },
];

export const db = {
    isAuth: true,
    locale: 'ua',
    owners: [
        {
            id: '728ed52f',
            owner: 'Johnson Jn ',
            estateType: 'house',
            address: 'city Washington Abram st, h.17',
            paymentHistory: paymentHistory,
            email: 'm00001@example.com',
        },
        {
            id: '128e452f',
            owner: 'Abrams S.D ',
            estateType: 'commercial',
            address: 'city Washington St.West st, h.15',
            paymentHistory: paymentHistory,
            email: 'm123@example.com',
        },
        {
            id: '228e452f',
            owner: 'Dr Lams D.J.',
            estateType: 'flat',
            address: 'city Washington St.East st, h.5',
            paymentHistory,
            email: 'm133@example.com',
        },
        {
            id: '728e0122f',
            owner: 'Johnson Jn',
            estateType: 'house',
            address: 'city Washington St.Abram st, h.17',
            paymentHistory,
            email: 'm00001@example.com',
        },
        {
            id: '128e452f',
            owner: 'Abrams S.D',
            estateType: 'house',
            address: 'city Washington St.West st, h.15',
            paymentHistory,
            email: 'm123@example.com',
        },
        {
            id: 'random1',
            owner: 'Doe John',
            estateType: 'flat',
            address: 'city Washington St.Main st, h.23',
            paymentHistory,
            email: 'm134@example.com',
        },
        {
            id: 'random2',
            owner: 'Smith L.',
            estateType: 'house',
            address: 'city Washington St.River st, h.2',
            paymentHistory,
            email: 'm135@example.com',
        },
        {
            id: 'random3',
            owner: 'Brown A.',
            estateType: 'other', // Since house is false and flat is not specified
            address: 'city Washington St.Lake st, h.9',
            paymentHistory,
            email: 'm136@example.com',
        },
        {
            id: 'random4',
            owner: 'Williams T.',
            estateType: 'flat',
            address: 'city Washington St.Park st, h.30',
            paymentHistory: paymentHistory,
            email: 'm137@example.com',
        },
        {
            id: 'random5',
            owner: 'Jones M.',
            estateType: 'house',
            address: 'city Washington St.Oak st, h.21',
            paymentHistory: paymentHistory,
            email: 'm138@example.com',
        },
        {
            id: 'random6',
            owner: 'Miller C.',
            estateType: 'flat',
            email: 'm139@example.com',
            address: 'city Washington St.Bridge st, h.15',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random7',
            owner: 'Garcia D.',
            estateType: 'house',
            email: 'm140@example.com',
            address: 'city Washington St.Hill st, h.40',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random8',
            owner: 'Moore R.',
            estateType: 'flat',
            email: 'm141@example.com',
            address: 'city Washington St.Snow st, h.6',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random9',
            owner: 'Jackson P.',
            estateType: 'house',
            email: 'm142@example.com',
            address: 'city Washington St.Pond st, h.35',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random10',
            owner: 'White S.',
            estateType: 'flat',
            email: 'm143@example.com',
            address: 'city Washington St.Mountain st, h.29',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random11',
            owner: 'Lee Q.',
            estateType: 'flat',
            email: 'm144@example.com',
            address: 'city Washington St.Beach st, h.13',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random12',
            owner: 'Harris Z.',
            estateType: 'house',
            email: 'm145@example.com',
            address: 'city Washington St.Forest st, h.1',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random13',
            owner: 'Clark W.',
            estateType: 'house',
            email: 'm146@example.com',
            address: 'city Washington St.Desert st, h.7',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random14',
            owner: 'Lewis Y.',
            estateType: 'flat',
            email: 'm147@example.com',
            address: 'city Washington St.Wind st, h.19',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random15',
            owner: 'Walker X.',
            estateType: 'house',
            email: 'm148@example.com',
            address: 'city Washington St.Cloud st, h.45',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random16',
            owner: 'Hall V.',
            estateType: 'flat',
            email: 'm149@example.com',
            address: 'city Washington St.Tower st, h.8',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random17',
            owner: 'Allen U.',
            estateType: 'house',
            email: 'm150@example.com',
            address: 'city Washington St.Plain st, h.55',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random18',
            owner: 'Scott T.',
            estateType: 'flat',
            email: 'm151@example.com',
            address: 'city Washington St.Wave st, h.34',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random19',
            owner: 'Young S.',
            estateType: 'house',
            email: 'm152@example.com',
            address: 'city Washington St.Meadow st, h.26',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random20',
            owner: 'Hernandez R.',
            estateType: 'flat',
            email: 'm153@example.com',
            address: 'city Washington St.Dream st, h.3',
            paymentHistory: paymentHistory,
        },
        {
            id: 'random21',
            owner: 'King Q.',
            estateType: 'flat',
            email: 'm154@example.com',
            address: 'city Washington St.Fantasy st, h.16',
            paymentHistory: paymentHistory,
        },
    ],
};
